name: Dead Code Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D dead_code -D unused_imports -D unused_variables -D unused_mut"

jobs:
  check-dead-code:
    name: Strict Dead Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-latest-cargo-dead-code-strict-${{ hashFiles('**/Cargo.lock') }}

      - name: Check for any dead code
        run: |
          echo "🔍 Running comprehensive dead code analysis..."
          echo "This check enforces our strict no-dead-code policy."
          echo ""

          # Run cargo check with dead code as errors
          echo "Running cargo check with dead_code warnings as errors..."
          if ! cargo check --all-targets --all-features; then
            echo ""
            echo "❌ Dead code detected during compilation!"
            echo "Please remove all unused code before submitting your PR."
            echo "See CONTRIBUTING.md for our dead code policy."
            exit 1
          fi

          echo "✅ cargo check passed - no dead code found during compilation"

      - name: Run clippy with strict dead code rules
        run: |
          echo ""
          echo "🔧 Running clippy with strict dead code detection..."

          if ! cargo clippy --all-targets --all-features -- \
            -D dead_code \
            -D unused_imports \
            -D unused_variables \
            -D unused_mut \
            -D unused_assignments \
            -D unused_macros \
            -D unused_allocation \
            -D unused_doc_comments \
            -D unused_extern_crates \
            -D unused_features \
            -D unused_labels \
            -D unused_parens \
            -D unused_braces \
            -D path_statements \
            -D unreachable_code \
            -D warnings; then
            echo ""
            echo "❌ Clippy detected dead/unused code!"
            echo ""
            echo "Our project maintains a strict no-dead-code policy."
            echo "Please remove all unused:"
            echo "  • Functions and methods"
            echo "  • Variables and parameters" 
            echo "  • Imports and dependencies"
            echo "  • Struct fields and enum variants"
            echo "  • Constants and static items"
            echo "  • Macros and modules"
            echo ""
            echo "If code is needed for future features:"
            echo "  • Create a separate branch"
            echo "  • File an issue for tracking"
            echo "  • Use feature flags if appropriate"
            echo ""
            echo "See CONTRIBUTING.md for more details on our dead code policy."
            exit 1
          fi

          echo "✅ Clippy passed - no dead code detected!"

      - name: Final validation
        run: |
          echo ""
          echo "🎉 All dead code checks passed!"
          echo "Your code meets our quality standards."
